# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='city',
        ),
    ]
