# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_town_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='region_town',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region_town', to='pokemon.Region'),
            preserve_default=False,
        ),
    ]
